//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenzenVerwaltungsTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbsenzenDBEntities : DbContext
    {
        public AbsenzenDBEntities()
            : base("name=AbsenzenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absenz> Absenzs { get; set; }
        public virtual DbSet<Klasse> Klasses { get; set; }
        public virtual DbSet<Lehrer> Lehrers { get; set; }
        public virtual DbSet<Modul> Moduls { get; set; }
        public virtual DbSet<Schueler> Schuelers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
