//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenzenVerwaltungsTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absenz
    {
        public int absenz_id { get; set; }
        public System.DateTime Datum { get; set; }
        public double Lektionen { get; set; }
        public int modul_id { get; set; }
        public int schueler_id { get; set; }
    
        public virtual Modul Modul { get; set; }
        public virtual Schueler Schueler { get; set; }
    }
}
